---
title: "21-Estimation_Geom"
output: github_document
---

## Estimation Functions
```{r}

## Function to get filename
get_filename <- function(config, rep, prefix = "Geom") {
  sprintf("%s_rep_%d_n_%d_p_%d.RData", prefix, rep, config$n, config$p)
}

## Using QUIC
quicr <- function(data, lambda) {
    p <- ncol(data)
    est  <- BigQuic(X = data, lambda=lambda, epsilon=1e-2, use_ram=TRUE, seed = NULL)
    est <- setNames(lapply(ls(envir=est), mget, envir=attr(unclass(est), '.xData')), ls(envir=est))
    path <-  lapply(seq(length(lambda)), function(i) {
                tmp <- est$precision_matrices[[1]][[i]][1:p,1:p]
                diag(tmp) <- 0
                as(tmp!=0, "lMatrix")
    })
    est$path <- path
    est
}

## Extraction Function
extract_categorized_optimal_info <- function(output) {
  # Initialize lists to store the categorized results
  optimal_indices <- list()
  optimal_lambdas <- list()
  selected_graphs <- list()
  act_sparsity <- list()

  # Extract the criteria from the output object
  criteria <- output[["criterion"]]

  # Loop through each criterion
  for (crit in criteria) {
    # Extract the criterion name
    crit_name <- crit[[1]]
  
    # Store the optimal index, lambda, and refit graph for the current criterion
    optimal_indices[[crit_name]] <- output[[crit_name]][["opt.index"]]
    optimal_lambdas[[crit_name]] <- output[[crit_name]][["opt.lambda"]]
    selected_graphs[[crit_name]] <- output[[crit_name]][["refit"]]
    act_sparsity[[crit_name]] <- output[[crit_name]][["sparsity"]]
  }

  # Create a list to store all categorized results
  categorized_results <- list(
    "optimal_indices" = optimal_indices,
    "optimal_lambdas" = optimal_lambdas,
    "selected_graphs" = selected_graphs,
    "act_sparsity" = act_sparsity,
    "additional_metrics" = output$additional
  )

  return(categorized_results)
}

# Lambda path plots
plot_lambda_path <- function(config, rep, prefix, dir_path, show) {
  plot_filename <- sprintf("%s_rep_%d_n_%d_p_%d.pdf", prefix, rep, config$n, config$p)
  pdf(file.path(dir_path, plot_filename), width = 8, height = 6)
  plot(out.p, legends = TRUE, show = show)
  dev.off()
}

```


## Run StARS, G-StARS, PG-StARS and Oracle with additional criteria
```{r}
# Required packages
#install.packages("htmltools")
#install.packages("devtools")
#install.packages("batchtools")
#devtools::install_github("zdk123/pulsar")
#install.packages("BigQuic")
#install.packages("corrplot")

library(corrplot)
library(BigQuic)
library(batchtools)
library(devtools)
library(htmltools)

# Define main directory paths
dir_path2 <- "/Users/bropc/Documents/LMU/Master Statistics and Data Science/Masterarbeit/R Master/StARS_Simulations/workflow/Storage_Estimation_Geom/"
#dir_path2 <- "C:/R Projekte/StARS_Simulations/workflow/Storage_Estimation_Geom"
dir_path_results <- file.path(dir_path2, "Results")

# Load settings
Geom_setting_path <- "/Users/bropc/Documents/LMU/Master Statistics and Data Science/Masterarbeit/R Master/StARS_Simulations/workflow/Storage_Settings/"
#Geom_setting_path <- "C:/R Projekte/StARS_Simulations/workflow/Storage_Settings/" 
Geom_settings_file <- file.path(Geom_setting_path, "Geom_settings.RData")
load(Geom_settings_file)

# Create Results directory if it doesn't exist
if (!dir.exists(dir_path_results)) {
  dir.create(dir_path_results)
}

# Main loop over each configuration and repetition
for (rep in 1:num_repetitions) {
  for (i in seq_along(configs)) {
    
    # Reinitialize or clear relevant variables
    out.p <- NULL
    out.esti <- list()
    
    config <- configs[[i]]
    
    # Prepare directories for storing results
    config_dir <- file.path(dir_path2, sprintf("config_n_%d_p_%d", config$n, config$p))
    rep_dir <- file.path(config_dir, sprintf("rep_%d", rep))
    lambda_dir <- file.path(rep_dir, "lambda_path_plots")

    # Create directories if they don't exist
    dir.create(config_dir, recursive = TRUE, showWarnings = FALSE)
    dir.create(lambda_dir, recursive = TRUE, showWarnings = FALSE)

    # Load the dataset for the current configuration and repetition
    filename <- get_filename(config, rep)
    print(paste("Loading data from:", filename))
    load(paste0(dir_path, "/", filename))
    
    quicargs <- list(lambda = lambda_path)  

    # Run batch pulsar
    options(mc.cores = 2) #Speed up by setting number of cores available
    options(batchtools.progress=TRUE, batchtools.verbose=FALSE)
    #resources <- list(mem="1GB", nodes="1", walltime="00:30:00") # number of computers or servers you are requesting for your job
    
    out.p <- Graphreg(
      data = Geom_data, 
      fun = quicr, 
      fargs = quicargs, 
      rep.num = N,
      thresh = 0.05,
      subsample.ratio = b,
      criterion=c('stars', 'gcd', 'gcd_prior', 'ghust', 'ghust_prior'), 
      lb.stars = TRUE, 
      ub.stars = TRUE, 
      seed = FALSE,
      refit = TRUE,
      prior_graph = true_graph,
      method = c("spearman", "kendall", "latentcor"),
      use_pseudo_count = TRUE
      #job.res = resources
    )
  
    out.esti <- extract_categorized_optimal_info(out.p)
    
    ## Adding Results lambda path and GCMs
    for (crit in out.p$criterion) {
      out.esti$raw_summary[[crit]] <- out.p[[crit]]$summary
      # Check if GCM is available for the current criterion and assign it if available
      if (!is.null(out.p[[crit]][["gcm"]])) {
        out.esti$GCM[[crit]] <- out.p[[crit]][["gcm"]]
      }
    }
    
    ## Adding gcm for true_graph 
    for (meth in c("spearman", "kendall", "latentcor")) {
      gcm_true <- my.gcvec(true_graph, orbind = c(0, 2, 5, 7, 8, 10, 11, 6, 9, 4, 1), method = meth, return_gcm = TRUE)
      gcm_true_pseudo <- my.gcvec(true_graph, orbind = c(0, 2, 5, 7, 8, 10, 11, 6, 9, 4, 1), method = meth,
                                  return_gcm = TRUE, pseudo_count = TRUE)
      out.esti$GCM[[paste("true_graph", meth, sep = "_")]] <- gcm_true
      out.esti$GCM[[paste("true_graph_pseudo", meth, sep = "_")]] <- gcm_true_pseudo
    }
    
    out.esti$selected_graphs[["null_graph"]] <- null_graph
    out.esti$selected_graphs[["true_graph"]] <- true_graph
    out.esti$act_sparsity[["null_graph"]] <- sum(null_graph) / (config$p * (config$p - 1))
    out.esti$act_sparsity[["true_graph"]] <- sum(true_graph) / (config$p * (config$p - 1))
    criterion <- unique(c(out.p$criterion, "null_graph"))
    out.esti$criterion <- criterion
    out.esti$additional_metrics$lb.index <- out.p[["stars"]][["lb.index"]]
    out.esti$additional_metrics$ub.index <- out.p[["stars"]][["ub.index"]]
    out.esti$premerge <- out.p$premerge
    out.esti$fullmodel <- out.p$est$path
    
    # Bounding down again Stars
    if (!is.null(out.esti$additional_metrics$lb.index)) {
      stars_bound <- out.esti[["additional_metrics"]][["ind_bound"]]
      out.esti$raw_summary$stars <- out.esti$raw_summary$stars[stars_bound]
    }

    plot_lambda_path(config, rep, "Plot_gcd", lambda_dir, show = c("stars", "gcd_spearman", "gcd_kendall", "gcd_latentcor",
                                                                   "gcd_pseudo_spearman", "gcd_pseudo_kendall",
                                                                   "gcd_pseudo_latentcor"))
    plot_lambda_path(config, rep, "Plot_gcd_prior", lambda_dir, show = c("stars", "gcd_prior_spearman", "gcd_prior_kendall", 
                                                                         "gcd_prior_latentcor", "gcd_prior_pseudo_spearman",
                                                                         "gcd_prior_pseudo_kendall", "gcd_prior_pseudo_latentcor"))
    
    # Save the results in the Results directory
    save(num_repetitions, configs, dir_path, dir_path2, dir_path_results, file = Geom_settings_file)
    result_filename <- get_filename(config, rep, "estimation")
    save(out.p, out.esti, true_graph, file = file.path(dir_path_results, result_filename))
  }
}

print("Estimation completed and plots saved!")



```




## Session info
```{r}
sessionInfo()
```




